몇 가지 개선사항을 담은 PR을 올려봅니다.
kimcore/chzzk-overlay pull request #1
Opened 2023-12-22 20:31 UTC by AiOO

작업하신 코딩 컨벤션을 맞추려고 하였으나 어긋나는 부분이 있을 수 있습니다. 궁금하신 점이나 고쳐야 할 부분은 언제든지 편하게 말씀 주시기 바랍니다. 그리고 제 변경으로 인해 혹시라도 실시간 방송에 피해가 가면 안 된다는 것을 잘 알고 있기 때문에, 변경점이 큰 만큼 충분히 안정성이 검증된 상태로 병합될 수 있도록 책임지고 도움을 드리겠습니다.

## 변경내역:

### 코드적인 부분:

- DOM을 직접 조작하는 것이 아닌 리액트 컴포넌트를 사용하도록 했습니다.
   - 원래 리액트 컴포넌트로 작업하시다가 [feat: use appendChild, add 5ms chat delay](https://github.com/kimcore/chzzk-overlay/commit/dfe8ee2e931bf7b2f2d58f928c3cf46234d3b3b9) 커밋에서 DOM으로 조작하도록 바꾸신 것을 보기는 했는데, 추후 편리한 개선을 위해서라도 리액트 컴포넌트를 활용하는 것이 더 안정적일 것이라고 판단하였습니다.
   - 훅과 메모를 활용하여 리렌더와 성능 이슈가 최대한 발생하지 않도록 고려하였습니다.
- 웹소켓, OBS 이벤트 핸들러 등 정리가 필요한 리소스들을 페이지를 닫을 때 잘 정리할 수 있도록 했습니다.

### 기능적인 부분:

- 채팅 목록이 순서에 맞게 나타날 수 있도록 하였습니다. 웹소켓에서 보내주는 데이터가 완전히 순서를 보장해주지는 않는 것 같더라고요.
- 채팅 지연 표시를 위해 사용하던 sleep 대신 채팅 목록 버퍼를 도입했습니다. 
   - 웹소켓에서 받은 채팅을 바로 렌더링하는 것이 아닌 채팅 목록 버퍼(useRef)에 넣습니다.
   - 75ms마다 채팅 목록 버퍼의 챗 하나를 꺼내서 렌더링을 해 줍니다.
   - 이는 채팅이 활발한 상황에서 일정한 속도로 채팅이 올라가는 것과, 채팅 목록의 순서를 보장해주는데 도움이 됩니다.
   - 탭이 절전 모드에 빠지거나 하면 렌더링이 지연되어 채팅이 밀물처럼 올라가는 증상이 생길 수 있으므로 1초 이상 렌더링이 지연된 경우 한 번에 렌더링을 하도록 작성했습니다. 이 동작은 최초 로딩 시 채팅을 한 번에 표시하는 데에도 사용됩니다.

좋은 코드에 기여할 수 있도록 저장소를 열어주셔서 감사드립니다. :bow:

2023-12-23 00:49 UTC, kimcore commented on app/[channelId]/ChatBox.tsx
> +                    pendingChatListRef.current = [...pendingChatListRef.current, ...chats].slice(-50)
isRecent일 경우 setChatList를 사용해 바로 띄워주는게 나을 듯 합니다.

2023-12-23 00:52 UTC, kimcore commented on app/[channelId]/ChatBox.tsx
> +                        .sort((a, b) => a.msgTime - b.msgTime)
Recent Chat의 경우 프로퍼티가 msgTime이 아닌 createTime 이라서, convertChat 함수에서 time을 불러온 후에 sort를 하는게 어떨까요?

2023-12-23 00:54 UTC, kimcore requested changes
좋은 기여 감사합니다! 확실히 DOM 보다는 이 방법이 훨씬 나은 듯 하네요.
코멘트 단 부분만 수정해주시면 바로 머지하도록 하겠습니다 :)

2023-12-23 04:50 UTC, AiOO commented on app/[channelId]/ChatBox.tsx
> +                    pendingChatListRef.current = [...pendingChatListRef.current, ...chats].slice(-50)
좋은 의견 감사드립니다! 바로 반영하였습니다.
[Use setChatList if recent chats received](https://github.com/kimcore/chzzk-overlay/pull/1/commits/85ec45eaefc82a1fbc80f0b3617f510e66f2853e)

2023-12-23 04:50 UTC, AiOO commented on app/[channelId]/ChatBox.tsx
> +                        .sort((a, b) => a.msgTime - b.msgTime)
다시 한 번 채팅이 활발한 방송에서 체크해보니, 보내주는 청크는 정렬이 된 상태가 보장이 되는 듯해서 정렬 로직을 삭제했습니다.
[Remove useless sort logic](https://github.com/kimcore/chzzk-overlay/pull/1/commits/1d5fab340fd9e68733c70b5e08d72e2adc0f9681)

2023-12-23 04:53 UTC, AiOO commented
리뷰 달아주신 것 이외에도 다음 수정이 진행되었습니다:

- 치지직 공식 페이지를 모사하여 핑 로직을 작성하였습니다. 20초간 통신이 없으면 핑을 보내는 것을 반복합니다.
   - [Implemented ping to prevent chat from freezing](https://github.com/kimcore/chzzk-overlay/pull/1/commits/4918ad24deea56ba61a096e06abd9e26897bfa35)
- 서버에서 보내는 핑에 대한 응답을 치지직 공식 페이지와 같게 맞추었습니다.

2023-12-23 05:30 UTC, merged

2023-12-24 03:41 UTC, AiOO commented
방금 녹두로님 방송 중에 문제가 생긴 느낌인데 ㅠㅠ 혹시 문제 계속 있으면 롤백해주세요 ㅜㅅㅜ...